encoding: utf-8

# seo
title: 秦东亮的个人驿站
description: coding change world
keywords: Java,ELK,Spark,Scala,Hadoop,Solr,Lucene
author: Qin Dong Liang

# "","/blog"
context: ""
scheme: "http"
domain: "blog.tmaize.net"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2018
beianhao: "京ICP备16016174号"

coderay:
  coderay_tab_width: 4
